Remove Serializable interface from GMP class
Trying to use `$gmp->serialize()` or `$gmp->unserialize()` as defined in the stubs will result in `Error: Call to undefined method GMP::serialize()`

PHP does not provide an object-oriented interface to manipulate GMP objects, only a procedural GMP API. 

See: https://www.php.net/manual/en/class.gmp.php

> _"No object-oriented interface is provided to manipulate GMP objects. Please use the procedural GMP API."_

This can be confirmed in the PHP source code, the GMP class does not implement the `Serializable` interface, see: https://github.com/php/php-src/blob/master/ext/gmp/gmp.c#L584

If `Serializable` interface was implemented in the PHP source code, then we would have expected to see `register_class_GMP(zend_ce_serializable)`.